export default {
  colors: {
    yellow: '#FFC70E',
    blue: '#00C3FF',
    white: '#FFF',
    black: '#000',
    darkergrey: '#666',
    text: '#999',
    grey: '#C8C8C8',
    red: '#FF6961',
    blacktransparent: 'rgba(0,0,0,0.5)',
  },
  fontSizes: {
    small: '0.75rem',
    regularSm: '0.875rem',
    regular: '1rem',
    regularL: '1.25rem',
    large: '1.5rem',
    largeX: '2rem',
    largeXX: '2.5rem',
  },
  margins: {
    smallX: '0.25rem',
    smallXX: '0.5rem',
    small: '0.75rem',
    regular: '1rem',
    medium: '1.25rem',
    large: '1.5rem',
    largeX: '2rem',
    largeXX: '2.5rem',
  },
};
